<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MahasiswaExport extends Model
{
  protected $table = 'mahasiswa_export';
  protected $fillable = [
    'id',
    'nim',
    'alamat',
    'nama',
    'telp',
    'email',
    'tahun_angkatan',

    'angkatan',

    'tanggal_masuk',
    'tempat_lahir',
    'tanggal_lahir',
    'tanggal_lahir_manual',
    'kelamin',
    'jurusan',
    'konsentrasi',
    'jenjang',
    'semester_mulai',
    'program',
    'agama',
    'warganegara',
    'negara',
    'status_awal_mahasiswa',
    'merupakan_pindahan',
    'pindahan_dari_kampus',
    'nama_prodi_pindah',
    'nim_pindahan',
    'pindah_dari_kampus_lama_di_semester',
    'pindah_ke_kampus_ini_masuk_semester',
    'tanggal_pindah',
    'sks_yang_diakui',
    'keterangan_pindah',
    'merupakan_alih_prodi',
    'nim_lama_sebelum_pindah',
    'sks_yang_diakui_pindah_prodi',
    'pindah_ke_prodi_ini_masuk_semester',
    'tanggal_pindah_prodi',
    'keterangan_pindah_prodi',
    'status_keluar',
    'no_ijazah_1',
    'no_ijazah_2',
    // 'no_akta_1',
    // 'no_akta_2',
    'tahun_wisuda',
    'tahun_lulus',
    'semester_lulus',
    'tanggal_lulus',
    'tanggal_yudisium',
    'tanggal_sk_rektor',
    'judul_skripsi',
    'predikat_kelulusan',
    'beasiswa_mahasiswa_miskin',
    'beasiswa_bidik_misi',
    'beasiswa_lain',
    // 'facebookid',
    // 'google_id',
    // 'twitter_id',
    // 'linkedin_id',
    'jenis_seleksi',
    'jenis_pembiayaan_mahasiswa',
    // 'username_ojs',
    // 'status_setelah_lulus',

    // 'status_domisili_setelah_lulus',
    // 'feeder',
    // 'idregpd',
    // 'lock_id',
    // 'token',
    // 'masa_studi',
    // 'link_validasi_eksternal',
    // 'nomor_skpi',
    // 'id_finger',
    'dosen_pa',
    'kelas',
    'nomor_ktp',
    'nama_ayah',
    'tanggal_lahir_ayah',
    'jenis_pekerjaan_ayah',
    'rata_rata_penghasilan_ayah',
    'jenjang_pendidikan_ayah',
    'nama_ibu',
    'tanggal_lahir_ibu',
    'jenis_pekerjaan_ibu',
    'rata_rata_penghasilan_ibu',
    'jenjang_pendidikan_ibu',
    'telp_rumah',
    'hp',
    'status',
    'nomor_ktp_ayah',
    'nomor_ktp_ibu',
    'npsn',
    'asal_pendidikan',
    'alamat_pendidikan_sebelumnya',
    'npwp',
    'no_kk',
    'rt',
    'rw',
    'kode_pos',
    'dusun_kampung',
    'desa_kelurahan',
    'kode_kecamatan',
    'kecamatan',
    'kota_kabupaten',
    'propinsi',
    'status_perkawinan',
    'jenis_tinggal_mahasiswa',
    'alat_transportasi_mahasiswa',
    'ukuran_jaket',
    'tinggi_badan',
    'berat_badan',
    'nirm',
    'nisn',
    'nama_sesuai_ijazah',
    'operator_hp',
    // 'foto',
    // 'ijazah',
    // 'transkrip_nilai',
    // 'ktp',
    // 'lampiran_ke_1',
    // 'lampiran_ke_2',
    // 'lampiran_ke_3',
    // 'lampiran_ke_4',
    // 'lampiran_ke_5',
    'semester',
    'tahap',
    'ips',
    'ipk',
    'sks',
    'sksk',
    // 'jumlah_login',
    // 'sejarah_login',
    'masa_studi_tahun',
    'masa_studi_bulan',
    'masa_studi_hari',
    'masa_studi_deskripsi',
    'no_urut_data',
    'filename',
  ];
}
