<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateMahasiswaExportTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('mahasiswa_export', function (Blueprint $table) {
            $table->string('id',20)->nullable();
            $table->string('nim',20)->unique();
            $table->string('alamat',250)->nullable();
            $table->string('nama',150)->nullable();
            $table->string('telp',50)->nullable();
            $table->string('email',100)->nullable();
            $table->string('tahun_angkatan',4)->nullable();
            $table->string('angkatan',4)->nullable();
            $table->string('tanggal_masuk',25)->nullable();
            $table->string('tempat_lahir',50)->nullable();
            $table->string('tanggal_lahir',15)->nullable();
            $table->string('tanggal_lahir_manual',50)->nullable();
            $table->string('kelamin',10)->nullable();
            $table->string('jurusan',50)->nullable();
            $table->string('konsentrasi',100)->nullable();
            $table->string('jenjang',20)->nullable();
            $table->string('semester_mulai',10)->nullable();
            $table->string('program',20)->nullable();
            $table->string('agama',20)->nullable();
            $table->string('warganegara',5)->nullable();
            $table->string('negara',50)->nullable();
            $table->string('status_awal_mahasiswa',20)->nullable();
            $table->boolean('merupakan_pindahan')->nullable();
            $table->string('pindahan_dari_kampus',100)->nullable();
            $table->string('nama_prodi_pindah',100)->nullable();
            $table->string('nim_pindahan',20)->nullable();
            $table->unsignedTinyInteger('pindah_dari_kampus_lama_di_semester')->nullable();
            $table->unsignedTinyInteger('pindah_ke_kampus_ini_masuk_semester')->nullable();
            $table->string('tanggal_pindah',15)->nullable();
            $table->unsignedTinyInteger('sks_yang_diakui')->nullable();
            $table->string('keterangan_pindah',200)->nullable();
            $table->boolean('merupakan_alih_prodi')->nullable();
            $table->string('nim_lama_sebelum_pindah',20)->nullable();
            $table->unsignedTinyInteger('sks_yang_diakui_pindah_prodi')->nullable();
            $table->unsignedTinyInteger('pindah_ke_prodi_ini_masuk_semester')->nullable();
            $table->string('tanggal_pindah_prodi',15)->nullable();
            $table->string('keterangan_pindah_prodi',200)->nullable();
            $table->string('status_keluar',50)->nullable();
            $table->string('no_ijazah_1',50)->nullable();
            $table->string('no_ijazah_2',50)->nullable();
            $table->string('no_akta_1',50)->nullable();
            $table->string('no_akta_2',50)->nullable();
            $table->string('tahun_wisuda',4)->nullable();
            $table->string('tahun_lulus',4)->nullable();
            $table->string('semester_lulus',10)->nullable();
            $table->string('tanggal_lulus',15)->nullable();
            $table->string('tanggal_yudisium',15)->nullable();
            $table->string('tanggal_sk_rektor',15)->nullable();
            $table->string('judul_skripsi',250)->nullable();
            $table->string('predikat_kelulusan',50)->nullable();
            $table->string('beasiswa_mahasiswa_miskin',100)->nullable();
            $table->string('beasiswa_bidik_misi',100)->nullable();
            $table->string('beasiswa_lain',100)->nullable();
            $table->string('facebookid',50)->nullable();
            $table->string('google_id',200)->nullable();
            $table->string('twitter_id',50)->nullable();
            $table->string('linkedin_id',50)->nullable();
            $table->string('jenis_seleksi',20)->nullable();
            $table->string('jenis_pembiayaan_mahasiswa',50)->nullable();
            $table->string('username_ojs',50)->nullable();
            $table->string('status_setelah_lulus',50)->nullable();
            $table->string('status_domisili_setelah_lulus',50)->nullable();
            $table->string('feeder')->nullable();
            $table->string('idregpd')->nullable();
            $table->string('lock_id')->nullable();
            $table->string('token')->nullable();
            $table->string('masa_studi',100)->nullable();
            $table->string('link_validasi_eksternal')->nullable();
            $table->string('nomor_skpi',50)->nullable();
            $table->string('id_finger')->nullable();
            $table->string('dosen_pa',150)->nullable();
            $table->string('kelas',5)->nullable();
            $table->string('nomor_ktp',50)->nullable();
            $table->string('nama_ayah',150)->nullable();
            $table->string('tanggal_lahir_ayah',15)->nullable();
            $table->string('jenis_pekerjaan_ayah',50)->nullable();
            $table->string('rata_rata_penghasilan_ayah',50)->nullable();
            $table->string('jenjang_pendidikan_ayah',50)->nullable();
            $table->string('nama_ibu',150)->nullable();
            $table->string('tanggal_lahir_ibu',15)->nullable();
            $table->string('jenis_pekerjaan_ibu',50)->nullable();
            $table->string('rata_rata_penghasilan_ibu',50)->nullable();
            $table->string('jenjang_pendidikan_ibu',50)->nullable();
            $table->string('telp_rumah',50)->nullable();
            $table->string('hp',50)->nullable();
            $table->string('status',10)->nullable();
            $table->string('nomor_ktp_ayah',30)->nullable();
            $table->string('nomor_ktp_ibu',30)->nullable();
            $table->string('npsn',50)->nullable();
            $table->string('asal_pendidikan',100)->nullable();
            $table->string('alamat_pendidikan_sebelumnya')->nullable();
            $table->string('npwp',20)->nullable();
            $table->string('no_kk',20)->nullable();
            $table->string('rt',5)->nullable();
            $table->string('rw',5)->nullable();
            $table->string('kode_pos',10)->nullable();
            $table->string('dusun_kampung',50)->nullable();
            $table->string('desa_kelurahan',50)->nullable();
            $table->string('kode_kecamatan',10)->nullable();
            $table->string('kecamatan',50)->nullable();
            $table->string('kota_kabupaten',50)->nullable();
            $table->string('propinsi',50)->nullable();
            $table->string('status_perkawinan',20)->nullable();
            $table->string('jenis_tinggal_mahasiswa',50)->nullable();
            $table->string('alat_transportasi_mahasiswa',50)->nullable();
            $table->string('ukuran_jaket',10)->nullable();
            $table->string('tinggi_badan',3)->nullable();
            $table->string('berat_badan',3)->nullable();
            $table->string('nirm',20)->nullable();
            $table->string('nisn',20)->nullable();
            $table->string('nama_sesuai_ijazah',150)->nullable();
            $table->string('operator_hp',20)->nullable();
            $table->string('foto')->nullable();
            $table->string('ijazah')->nullable();
            $table->string('transkrip_nilai')->nullable();
            $table->string('ktp')->nullable();
            $table->string('lampiran_ke_1')->nullable();
            $table->string('lampiran_ke_2')->nullable();
            $table->string('lampiran_ke_3')->nullable();
            $table->string('lampiran_ke_4')->nullable();
            $table->string('lampiran_ke_5')->nullable();
            $table->unsignedTinyInteger('semester')->nullable();
            $table->unsignedTinyInteger('tahap')->nullable();
            $table->float('ips',6,4)->nullable();
            $table->float('ipk',6,4)->nullable();
            $table->unsignedTinyInteger('sks')->nullable();
            $table->unsignedTinyInteger('sksk')->nullable();
            $table->unsignedInteger('jumlah_login')->nullable();
            $table->text('sejarah_login')->nullable();
            $table->unsignedTinyInteger('masa_studi_tahun')->nullable();
            $table->unsignedTinyInteger('masa_studi_bulan')->nullable();
            $table->unsignedTinyInteger('masa_studi_hari')->nullable();
            $table->string('masa_studi_deskripsi',150)->nullable();
            $table->unsignedInteger('no_urut_data')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('mahasiswa_export');
    }
}
